### ISSUE TITLE
Issue with "containers" in @site/api/cloud/cwpp/containers.mdx

### ISSUE THREAD

**Issue by ethrlrnr** [PaloAltoNetworks/prisma.pan.dev#101]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

It is not clear what "fields" can be used for filtering. Please, include information about all the fields that can be used.

**Comment by csestito** [comment]
@iansk can you take a look at this?
