### ISSUE TITLE
Issue with "CWPP API" in @site/api/cloud/cwpp/cwpp-home.md

### ISSUE THREAD

**Issue by Pubs-MV** [PaloAltoNetworks/prisma.pan.dev#105]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

The content in this topic needs some fixes and additional information.

## Suggested fix

Here is what I suggest:
The Prisma Cloud Workload Protection APIs enable both automation and integration. Use the REST APIs to set up, configure, reconfigure, and deploy Prisma Cloud Compute components that enable you to secure your host, container, and serverless computing environments against vulnerabilities, malware, and compliance violations. You can also use it to extract data and integrate it with monitoring, alerting, and other systems in your environment.

For information on how to access the APIs, see https://prisma.pan.dev/docs/cloud/cwpp/cwpp-gs.
And if you are using the self-hosted version (Prisma Cloud Compute Edition), see https://prisma.pan.dev/docs/cloud/cwpp/porting-guide for the differences between versions 21.04 and 20.12.

**Comment by iansk** [comment]
Fixed in the update that will go live on Jun 14.
