### ISSUE TITLE
Issue with "IP Allow List API" in @site/api/cloud/cspm/ipallowlist.mdx

### ISSUE THREAD

**Issue by will-schneble** [PaloAltoNetworks/prisma.pan.dev#109]
## Describe the problem

1. Created a [network list](https://prisma.pan.dev/api/cloud/cspm/ipallow-list#operation/add-a-network) called "example-dev"
  * :warning: the `cidrs` field is not returned in the response
2. [Added cidr](https://prisma.pan.dev/api/cloud/cspm/ipallow-list#operation/add-cidr-block) "54.1.1.253/32" to the list "example-dev"
3. Created a new network list called "example-prod"
4. Added cidr "54.1.1.253/32" to the list "example-prod"
  * :warning: 400 returned, adding any other public IP works as expected. I am left to assume that CIDRs must be unique across network lists but this isn't expected since each network list and cidr object has a uuid.

## Suggested fix

1. Either update the docs to reflect that CIDRs must be globally unique or allow for the same CIDRs to be added across different network lists.
2. Update the docs to reflect that the `cidrs` field is not returned in the [create network list](https://prisma.pan.dev/api/cloud/cspm/ipallow-list#operation/add-a-network) API return

**Comment by debbm** [comment]
Thanks for this feedback. I verified the use case and updated the docs for [Add Network](https://prisma.pan.dev/api/cloud/cspm/ipallow-list#operation/add-a-network) and [Add CIDR](https://prisma.pan.dev/api/cloud/cspm/ipallow-list#operation/add-cidr-block) to:

- Reflect that  the response object for [Add Network](https://prisma.pan.dev/api/cloud/cspm/ipallow-list#operation/add-a-network) doesn't include CIDR blocks
- CIDR blocks cannot overlap other CIDR blocks in your networks.
