### ISSUE TITLE
Issue with "policies"

### ISSUE THREAD

**Issue by camachomaria** [PaloAltoNetworks/prisma.pan.dev#250]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

The page https://prisma.pan.dev/api/cloud/cwpp/policies, and other sibling pages under API Cloud, do not open correctly, but instead, they show an error message.

"API version": "22.06.179" 

For previous API versions, these pages open as expected.

"Something went wrong...
this.description.search is not a function. (In 'this.description.search(/^##?\s+/m)', 'this.description.search' is undefined)"

There is also a stack trace on the page:

mn@https://prisma.pan.dev/assets/js/common.f1a889d2.js:41:621854
Zr@https://prisma.pan.dev/assets/js/common.f1a889d2.js:41:645201
il@https://prisma.pan.dev/assets/js/common.f1a889d2.js:1217:710070
@https://prisma.pan.dev/assets/js/common.f1a889d2.js:118:657044
Ti@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:392250
$i@https://prisma.pan.dev/assets/js/common.f1a889d2.js:118:657002
li@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:387546
Hi@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:397065
Nl@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:426898
Cl@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:426826
Al@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:426689
wl@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:423676
wl@[native code]
@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:373465
@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:481228
Xo@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:373411
Ko@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:373346
hl@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:421061
Ri@https://prisma.pan.dev/assets/js/main.03a4108b.js:2:392843
Ri@[native code]
@https://prisma.pan.dev/assets/js/common.f1a889d2.js:118:656765
generatorResume@[native code]
i@https://prisma.pan.dev/assets/js/common.f1a889d2.js:118:656813
promiseReactionJob@[native code]

ReDoc Version: 2.0.0-rc.64 
Commit: 3b576c8

**Comment by csestito** [comment]
Hi @camachomaria, this should be resolved now, please reopen the issue if you are still facing problems. Thanks!
