### ISSUE TITLE
Issue with "defenders"

### ISSUE THREAD

**Issue by pasqua1e** [PaloAltoNetworks/prisma.pan.dev#251]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

The page https://prisma.pan.dev/api/cloud/cwpp/defenders/ doesn't load correctly. It seems all the pages underneath also fail to load.

## Suggested fix

Not sure about the fix

**Comment by csestito** [comment]
This has been fixed. Please let us know if you see the issue again.
