### ISSUE TITLE
Issue with "Welcome to the Prisma Cloud APIs"

### ISSUE THREAD

**Issue by OzNetNerd** [PaloAltoNetworks/prisma.pan.dev#265]
## Describe the problem

We don't have a link to the Code Security API docs on the ["Welcome to the Prisma Cloud APIs"](https://prisma.pan.dev/api/cloud/) page.

## Suggested fix

Can we please add [this link](https://prisma.pan.dev/api/cloud/code/) to the aforementioned page?

**Comment by 3agpot** [comment]
The change addressing this issue has been merged and deployed.
@csestito, can we close this issue?

**Comment by OzNetNerd** [comment]
LGTM
