### ISSUE TITLE
dark mode source example unreadable 

### ISSUE THREAD

**Issue by solalraveh** [PaloAltoNetworks/prisma.pan.dev#44]
We'll need to have a look the dark mode and how some quote sections look like which are unreadable, like:
![image](https://user-images.githubusercontent.com/7217044/103652842-fb376400-4f63-11eb-870e-dac1799cf4b5.png)

vs
![image](https://user-images.githubusercontent.com/7217044/103652865-01c5db80-4f64-11eb-91f3-b25e55b04f3b.png)

(compare all 'twistcli' entries). it's the stuff wrapped with these ticks: `
I'll have a look at what can be done and make a PR for it to be tied here, but we might need Charlie's additional help with this.

**Comment by sserrata** [comment]
Hi @solalraveh, we have a fix for this implemented on our other pan.dev sites. Basically, it's a CSS override. I'll open a PR shortly but another avenue might be to upgrade the underlying UI library to a more recent version.

**Comment by solalraveh** [comment]
The example PR looks very good! Switching to dark mode works great now.
Same goes for the new RQL "code" blocks.

**Comment by csestito** [comment]
fixed in #51
