### ISSUE TITLE
Move copy button to a place not hidden

### ISSUE THREAD

**Issue by solalraveh** [PaloAltoNetworks/prisma.pan.dev#45]
There's an excellent way to copy long queries with one button, instead of using cursor to highlight.
However, one doesn't know it's there till one hovers the cell:
![image](https://user-images.githubusercontent.com/7217044/103653160-6a14bd00-4f64-11eb-96d6-cc4542d5f644.png)

then hovering:
![image](https://user-images.githubusercontent.com/7217044/103653180-726cf800-4f64-11eb-8825-3802e0e10e40.png)

Suggesting to make it un-hidden for ode blocks and for better visibility potentially under the code block, not in it, as it might not be properly visible.

**Comment by sserrata** [comment]
Hi @solalraveh, thanks for opening this issue. I'll bring the feedback to the broader team for discussion and will update this thread once we come to a decision.

**Comment by solalraveh** [comment]
Thanks @sserrata !
Adding one more suggestion on this one: either to make each copy click up a counter, or have another "like" button of sorts, so we can track which ones were amazing for end users and by doing that, PMs can see that some community queries/policies are worthy for OOB nature, without the need to open a feature request...
