### ISSUE TITLE
Issue with "21.04 Porting Guide" in @site/docs/cloud/cwpp/porting_guide.md

### ISSUE THREAD

**Issue by wahaajsiddiqui** [PaloAltoNetworks/prisma.pan.dev#87]
Thank you for taking the time to help us improve our documentation! Please describe the problem and a suggested fix below and we'll get back to you as soon as we can. --DevRel

## Describe the problem

For Add Registry Spec API, "collections" param is required to make the call. It is not mentioned in the porting guide so the customer reported us the issue in the documentation. 

## Suggested fix

curl -k \
  -u <USER> \
  -H 'Content-Type: application/json' \
  -X POST \
  -d '
  {
    "version": "2",
    "registry": "",
    "repository": "library/alpine",
    "tag": "16.04",
    "os": "linux",
    "cap": 5,
    "hostname": "",
    "scanners": 2,
    "collections": ["Test"],
  } ' \
  https://<CONSOLE>:8083/api/v1/settings/registry

**Comment by iansk** [comment]
This has been fixed.

See https://prisma.pan.dev/api/cloud/cwpp/settings#operation/post-settings-registry
